"""Configuration for the MIDAS vector retargeter."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping, Sequence

from .coupling import FIXED_PASSIVE_MODE, normalize_coupling_mode
from .constants import (
    ACTIVE_JOINT_NAMES,
    DEFAULT_TARGET_LINK_HUMAN_INDICES,
    DEFAULT_TARGET_ORIGIN_LINK_NAMES,
    DEFAULT_TARGET_TASK_LINK_NAMES,
)
from .model import MIDAS_RIGHT_HAND, HandModel
from .paths import default_urdf_path
from .tuning import RetargeterTuning
from .urdf import with_tip_links

#: Analytic geometric map only. The default. Needs no dex_retargeting, no
#: torch and no URDF: the analytic layer writes all 13 actuated joints itself.
ANALYTIC_MODE = "analytic"
#: Pure dex-retargeting vector optimizer, analytic layer off. The honest A/B.
VECTOR_MODE = "vector"
#: Optimizer first, analytic layer overwrites the joints it owns. This is the
#: historical behaviour, kept for regression parity. Note the optimizer's
#: solution is fully overwritten for every actuated joint, so it contributes
#: nothing to the command; prefer ``analytic`` unless comparing against history.
REFINE_MODE = "refine"
SUPPORTED_RETARGET_MODES = (ANALYTIC_MODE, VECTOR_MODE, REFINE_MODE)


def normalize_retarget_mode(mode: str) -> str:
    normalized = str(mode).lower()
    if normalized not in SUPPORTED_RETARGET_MODES:
        raise ValueError(
            f"Unsupported mode={mode!r}. Expected one of {SUPPORTED_RETARGET_MODES}."
        )
    return normalized


@dataclass(frozen=True)
class MidasRetargeterConfig:
    """MIDAS-specific wrapper config around ``dex_retargeting``.

    The default uses option 1: optimize active MIDAS joints only and keep the
    passive DIP/linkage joints fixed in the retargeting FK model. Simulation
    handles those through MJCF closed-loop constraints; hardware handles them
    through the API PIP-DIP lookup.

    Tune this class for optimizer behavior: target links, human landmark
    indices, global scaling, and solver losses. Tune ``RetargeterTuning`` for
    operator-facing finger/thumb response after optimization.
    """

    # Path discovery: by default the package finds sibling midas_hand_mujoco.
    urdf_path: str | Path | None = None
    mujoco_repo: str | Path | None = None

    # Optimizer target definition. These names should match the retargeting
    # URDF generated by ``urdf.with_tip_links``.
    target_joint_names: Sequence[str] = ACTIVE_JOINT_NAMES
    target_origin_link_names: Sequence[str] = DEFAULT_TARGET_ORIGIN_LINK_NAMES
    target_task_link_names: Sequence[str] = DEFAULT_TARGET_TASK_LINK_NAMES
    target_link_human_indices: Sequence[Sequence[int]] = DEFAULT_TARGET_LINK_HUMAN_INDICES

    # TUNE: solver-level scaling and robust-loss widths. These are passed
    # directly to dex-retargeting's vector optimizer.
    scaling_factor: float = 1.15
    normal_delta: float = 4e-3
    huber_delta: float = 2e-2
    low_pass_alpha: float = 1.0
    has_joint_limits: bool = True

    # Passive-joint handling:
    #   fixed_passive: option 1, passive joints are fixed during FK.
    #   pip_dip_lookup: option 2, adaptor fills passive DIP/linkage from PIP.
    passive_fixed_qpos: Mapping[str, float] = field(default_factory=dict)
    coupling_mode: str = FIXED_PASSIVE_MODE
    pip_dip_lookup_path: str | Path | None = None

    # Which retargeting method drives the actuated joints. See the module
    # constants above. Default is the analytic geometric map.
    mode: str = ANALYTIC_MODE

    # Joint names and limits. Solver-free, so the analytic path needs no URDF.
    hand_model: HandModel = MIDAS_RIGHT_HAND

    # MIDAS-specific landmark correction layer. In ``refine`` mode, disabling
    # these yields pure optimizer output; in ``analytic`` mode disabling them
    # would leave the affected joints unwritten (commanding 0.0 rad = fully
    # extended), so it is rejected in __post_init__.
    thumb_postprocess: bool = True
    finger_postprocess: bool = True
    tuning: RetargeterTuning = field(default_factory=RetargeterTuning)

    def __post_init__(self) -> None:
        # Frozen dataclass: normalize through object.__setattr__ so the
        # canonical value is stored once instead of re-derived at each use.
        object.__setattr__(self, "mode", normalize_retarget_mode(self.mode))
        object.__setattr__(
            self, "coupling_mode", normalize_coupling_mode(self.coupling_mode)
        )

        if self.mode == VECTOR_MODE and (self.thumb_postprocess or self.finger_postprocess):
            object.__setattr__(self, "thumb_postprocess", False)
            object.__setattr__(self, "finger_postprocess", False)

        if self.mode == ANALYTIC_MODE and not (
            self.thumb_postprocess and self.finger_postprocess
        ):
            disabled = [
                name
                for name, on in (
                    ("finger_postprocess", self.finger_postprocess),
                    ("thumb_postprocess", self.thumb_postprocess),
                )
                if not on
            ]
            raise ValueError(
                f"mode={ANALYTIC_MODE!r} requires the analytic layer, but "
                f"{' and '.join(disabled)} is disabled. Nothing would write "
                "those joints, so they would command 0.0 rad (fully extended) "
                "— a real motion on hardware. Use mode='vector' for pure "
                "optimizer output, or mode='refine' to mix the two."
            )

    @property
    def uses_optimizer(self) -> bool:
        """Whether this config needs dex_retargeting (and so torch/pinocchio)."""

        return self.mode in (VECTOR_MODE, REFINE_MODE)

    def resolved_urdf_path(self) -> Path:
        if self.urdf_path is not None:
            path = Path(self.urdf_path).expanduser().resolve()
            if not path.exists():
                raise FileNotFoundError(f"MIDAS hand URDF does not exist: {path}")
            return path
        return default_urdf_path(self.mujoco_repo)

    def to_dex_config_dict(self) -> dict:
        return {
            "type": "vector",
            "urdf_path": with_tip_links(str(self.resolved_urdf_path())),
            "target_joint_names": list(self.target_joint_names),
            "target_origin_link_names": list(self.target_origin_link_names),
            "target_task_link_names": list(self.target_task_link_names),
            "target_link_human_indices": [
                list(row) for row in self.target_link_human_indices
            ],
            "scaling_factor": float(self.scaling_factor),
            "normal_delta": float(self.normal_delta),
            "huber_delta": float(self.huber_delta),
            "low_pass_alpha": float(self.low_pass_alpha),
            "has_joint_limits": bool(self.has_joint_limits),
        }

    def build_dex_config(self):
        try:
            from dex_retargeting.retargeting_config import RetargetingConfig
        except ImportError as exc:
            raise ImportError(
                "Could not import dex_retargeting. Install this package with "
                "`pip install -e .` so dex_retargeting and torch are installed."
            ) from exc

        return RetargetingConfig.from_dict(self.to_dex_config_dict())
