"""Configuration for the MIDAS vector retargeter."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from .constants import (
    ACTIVE_JOINT_NAMES,
    DEFAULT_TARGET_LINK_HUMAN_INDICES,
    DEFAULT_TARGET_ORIGIN_LINK_NAMES,
    DEFAULT_TARGET_TASK_LINK_NAMES,
)
from .coupling import (
    FIXED_PASSIVE_MODE,
    PIP_DIP_LOOKUP_MODE,
    normalize_coupling_mode,
)
from .model import MIDAS_RIGHT_HAND, HandModel
from .paths import default_urdf_path
from .tuning import RetargeterTuning
from .urdf import with_tip_links

#: Analytic geometric map only. The default. Needs no dex_retargeting, no
#: torch and no URDF: the analytic layer writes all 13 actuated joints itself.
ANALYTIC_MODE = "analytic"
#: Pure dex-retargeting vector optimizer, analytic layer off. The honest A/B.
VECTOR_MODE = "vector"
#: Optimizer first, analytic layer overwrites the joints it owns. This is the
#: historical behaviour, kept for regression parity. Note the optimizer's
#: solution is fully overwritten for every actuated joint, so it contributes
#: nothing to the command; prefer ``analytic`` unless comparing against history.
REFINE_MODE = "refine"
#: DexPilot optimizer: optimizes six pairwise INTER-FINGERTIP vectors plus four
#: palm-rooted ones, so unlike every other mode it controls where the fingertips
#: sit relative to each other. Analytic layer off. Needs the [vector] extra.
DEXPILOT_MODE = "dexpilot"
SUPPORTED_RETARGET_MODES = (ANALYTIC_MODE, VECTOR_MODE, REFINE_MODE, DEXPILOT_MODE)

#: Modes that drive the joints purely from the optimizer.
_OPTIMIZER_ONLY_MODES = (VECTOR_MODE, DEXPILOT_MODE)
#: Every mode whose fingertip FK must model the passive four-bar coupling.
_OPTIMIZER_MODES = (VECTOR_MODE, REFINE_MODE, DEXPILOT_MODE)


def normalize_retarget_mode(mode: str) -> str:
    normalized = str(mode).lower()
    if normalized not in SUPPORTED_RETARGET_MODES:
        raise ValueError(f"Unsupported mode={mode!r}. Expected one of {SUPPORTED_RETARGET_MODES}.")
    return normalized


@dataclass(frozen=True)
class MidasRetargeterConfig:
    """MIDAS-specific wrapper config around ``dex_retargeting``.

    The default uses option 1: optimize active MIDAS joints only and keep the
    passive DIP/linkage joints fixed in the retargeting FK model. Simulation
    handles those through MJCF closed-loop constraints; hardware handles them
    through the API PIP-DIP lookup.

    Tune this class for optimizer behavior: target links, human landmark
    indices, global scaling, and solver losses. Tune ``RetargeterTuning`` for
    operator-facing finger/thumb response after optimization.
    """

    # Path discovery: by default the package finds sibling midas_hand_mujoco.
    urdf_path: str | Path | None = None
    mujoco_repo: str | Path | None = None

    # Optimizer target definition. These names should match the retargeting
    # URDF generated by ``urdf.with_tip_links``.
    target_joint_names: Sequence[str] = ACTIVE_JOINT_NAMES
    target_origin_link_names: Sequence[str] = DEFAULT_TARGET_ORIGIN_LINK_NAMES
    target_task_link_names: Sequence[str] = DEFAULT_TARGET_TASK_LINK_NAMES
    target_link_human_indices: Sequence[Sequence[int]] = DEFAULT_TARGET_LINK_HUMAN_INDICES

    # TUNE: solver-level scaling and robust-loss widths. These are passed
    # directly to dex-retargeting's vector optimizer.
    scaling_factor: float = 1.15
    normal_delta: float = 4e-3
    huber_delta: float = 2e-2
    low_pass_alpha: float = 1.0
    has_joint_limits: bool = True

    # Passive-joint handling:
    #   fixed_passive: option 1, passive joints are fixed during FK.
    #   pip_dip_lookup: option 2, adaptor fills passive DIP/linkage from PIP.
    passive_fixed_qpos: Mapping[str, float] = field(default_factory=dict)
    #: ``None`` picks per mode: the analytic map never reads passive joints, so
    #: it defaults to ``fixed_passive`` and stays dependency-free, while the
    #: Cartesian modes default to ``pip_dip_lookup`` because they must not.
    coupling_mode: str | None = None
    pip_dip_lookup_path: str | Path | None = None

    # Which retargeting method drives the actuated joints. See the module
    # constants above. Default is the analytic geometric map.
    mode: str = ANALYTIC_MODE

    # DexPilot target definition. The fingertip frames do not exist in the
    # source URDF and are injected by ``urdf.with_tip_links``; their offsets
    # are CAD estimates, and in this mode they are load-bearing because the
    # solver aims at them directly. Measure them on the real hand.
    # DexPilot compares 3D vectors against the robot's own frame, so unlike
    # every other mode it is orientation-sensitive. Re-expressing the input in
    # the operator's palm basis makes it frame-invariant; disable only if you
    # are feeding landmarks already in the robot's palm frame.
    palm_frame_input: bool = True

    wrist_link_name: str = "palm_base"

    # --- thumb compensation (dexpilot only) ---------------------------------
    # The MIDAS thumb is proportionally LONG: palm_base->thumb_tip is 180.1 mm
    # against index 218.0 mm, a ratio of 0.83, where a human's is ~0.58. Two
    # segments have no human counterpart — a 41.4 mm palm_base->thumb_cmc_roll
    # offset and a 24.7 mm cmc_roll->cmc_side CMC mechanism. Comparing the
    # operator's wrist->thumb-tip against the robot's palm->thumb-tip therefore
    # forces the robot to curl its thumb to shorten itself, which is what makes
    # the MCP and DIP bend to unnatural angles.

    #: Compare the thumb against this robot link instead of ``wrist_link_name``,
    #: dropping the two non-anatomical offsets above. ``None`` keeps the legacy
    #: palm-rooted comparison. Measured on a real glove trace: thumb bend 0.63
    #: -> 0.37 rad and still-hand jitter 0.416 -> 0.163 rad, for +1.0 mm of
    #: inter-fingertip error.
    thumb_root_link: str | None = "thumb_cmc_side"

    #: Constrain the thumb MCP/DIP to flexion only, as the analytic map already
    #: does (``postprocess.THUMB_MCP_RANGE``). The physical joint CAN
    #: hyperextend, so this is a teleop policy — natural posture over reachable
    #: workspace — not a joint limit. Measured: S-curve postures 42% -> 14%,
    #: MCP hyperextension +0.60 -> +0.00 rad, at no cost to fingertip accuracy.
    thumb_flexion_only: bool = True
    finger_tip_link_names: Sequence[str] = (
        "thumb_tip",
        "index_tip",
        "middle_tip",
        "ring_tip",
    )

    # Joint names and limits. Solver-free, so the analytic path needs no URDF.
    hand_model: HandModel = MIDAS_RIGHT_HAND

    # MIDAS-specific landmark correction layer. In ``refine`` mode, disabling
    # these yields pure optimizer output; in ``analytic`` mode disabling them
    # would leave the affected joints unwritten (commanding 0.0 rad = fully
    # extended), so it is rejected in __post_init__.
    thumb_postprocess: bool = True
    finger_postprocess: bool = True
    tuning: RetargeterTuning = field(default_factory=RetargeterTuning)

    def __post_init__(self) -> None:
        # Frozen dataclass: normalize through object.__setattr__ so the
        # canonical value is stored once instead of re-derived at each use.
        object.__setattr__(self, "mode", normalize_retarget_mode(self.mode))
        # Resolve the passive-joint model. This matters far more for the
        # Cartesian modes than it looks: with fixed_passive the DIP joints are
        # held at 0 during FK, so the fingertip the solver aims at is up to
        # 59 mm from where the real one goes once the finger curls, because the
        # four-bar linkage swings the distal phalanx with the PIP. Measured on
        # the index finger: 23 mm at PIP -0.3, 48 mm at -0.9, 59 mm at -1.45.
        # That dwarfs every other error in the pipeline, so the vector modes
        # default to modelling the real coupling.
        coupling = self.coupling_mode
        if coupling is None:
            coupling = (
                PIP_DIP_LOOKUP_MODE
                if self.mode in _OPTIMIZER_MODES
                else FIXED_PASSIVE_MODE
            )
        object.__setattr__(self, "coupling_mode", normalize_coupling_mode(coupling))

        if self.mode in _OPTIMIZER_ONLY_MODES and (
            self.thumb_postprocess or self.finger_postprocess
        ):
            object.__setattr__(self, "thumb_postprocess", False)
            object.__setattr__(self, "finger_postprocess", False)

        if self.mode == ANALYTIC_MODE and not (self.thumb_postprocess and self.finger_postprocess):
            disabled = [
                name
                for name, on in (
                    ("finger_postprocess", self.finger_postprocess),
                    ("thumb_postprocess", self.thumb_postprocess),
                )
                if not on
            ]
            raise ValueError(
                f"mode={ANALYTIC_MODE!r} requires the analytic layer, but "
                f"{' and '.join(disabled)} is disabled. Nothing would write "
                "those joints, so they would command 0.0 rad (fully extended) "
                "— a real motion on hardware. Use mode='vector' for pure "
                "optimizer output, or mode='refine' to mix the two."
            )

        if self.mode != DEXPILOT_MODE:
            # Fail loudly rather than silently ignoring a setting that only the
            # DexPilot objective can act on.
            for name, default in (
                ("thumb_root_link", "thumb_cmc_side"),
                ("thumb_flexion_only", True),
            ):
                if getattr(self, name) != default:
                    raise ValueError(
                        f"{name} only applies to mode={DEXPILOT_MODE!r}, "
                        f"not mode={self.mode!r}."
                    )

    @property
    def uses_optimizer(self) -> bool:
        """Whether this config needs dex_retargeting (and so torch/pinocchio)."""

        return self.mode in (VECTOR_MODE, REFINE_MODE, DEXPILOT_MODE)

    def resolved_urdf_path(self) -> Path:
        if self.urdf_path is not None:
            path = Path(self.urdf_path).expanduser().resolve()
            if not path.exists():
                raise FileNotFoundError(f"MIDAS hand URDF does not exist: {path}")
            return path
        return default_urdf_path(self.mujoco_repo)

    def to_dex_config_dict(self) -> dict:
        if self.mode == DEXPILOT_MODE:
            return self._to_dexpilot_config_dict()
        return {
            "type": "vector",
            "urdf_path": with_tip_links(str(self.resolved_urdf_path())),
            "target_joint_names": list(self.target_joint_names),
            "target_origin_link_names": list(self.target_origin_link_names),
            "target_task_link_names": list(self.target_task_link_names),
            "target_link_human_indices": [list(row) for row in self.target_link_human_indices],
            "scaling_factor": float(self.scaling_factor),
            "normal_delta": float(self.normal_delta),
            "huber_delta": float(self.huber_delta),
            "low_pass_alpha": float(self.low_pass_alpha),
            "has_joint_limits": bool(self.has_joint_limits),
        }

    def _to_dexpilot_config_dict(self) -> dict:
        """DexPilot config. Solver knobs come from the live tuning profile.

        The human landmark indices are deliberately left to the optimizer's
        default (wrist + the four fingertips, MediaPipe 0/4/8/12/16); passing
        our own would silently override its pairwise structure.
        """

        dexpilot = self.tuning_profile.dexpilot
        # Only the keys RetargetingConfig actually forwards to
        # DexPilotOptimizer. It does NOT forward huber_delta, normal_delta,
        # eta1 or eta2 for this type, so those keep the optimizer's defaults at
        # construction and are pushed live each frame by the retargeter
        # instead — which is what makes them tunable at all.
        return {
            "type": "dexpilot",
            "urdf_path": with_tip_links(str(self.resolved_urdf_path())),
            "wrist_link_name": self.wrist_link_name,
            "finger_tip_link_names": list(self.finger_tip_link_names),
            "target_joint_names": list(self.target_joint_names),
            "scaling_factor": float(dexpilot.scaling_factor),
            "project_dist": float(dexpilot.project_dist),
            "escape_dist": float(dexpilot.escape_dist),
            "low_pass_alpha": float(dexpilot.low_pass_alpha),
            "has_joint_limits": bool(self.has_joint_limits),
        }

    @property
    def tuning_profile(self):
        """``tuning`` as a RetargetProfile, whatever form it was supplied in."""

        from .params import RetargetProfile
        from .postprocess import as_profile

        if isinstance(self.tuning, RetargetProfile):
            return self.tuning
        return as_profile(self.tuning)

    def build_dex_config(self):
        try:
            from dex_retargeting.retargeting_config import RetargetingConfig
        except ImportError as exc:
            raise ImportError(
                "Could not import dex_retargeting. Install this package with "
                "`pip install -e .` so dex_retargeting and torch are installed."
            ) from exc

        return RetargetingConfig.from_dict(self.to_dex_config_dict())
